config/routes.rb
Rails.application.routes.draw do
  root "portfolio#index"
  resources :contacts, only: [:new, :create ]
  get '/contacts', to: 'contacts#new', as: 'contact'
  get 'contacts/sent'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name,      validate: true
  attribute :email,     validate: /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message,   validate: true
  attribute :nickname,  captcha: true

  def headers
    {
      to: "remcojonk@hotmail.com", # change this to be the email you want sent to
      subject: "Railscoder Contact Form",
      from: "remcojonk@gmail.com",  # change this to be the email it is coming from
      reply_to: %("#{name}" <#{email}>)
    }
  end
end

app/models/project.rb
class Project < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def default_url_options
    { host: ENV["DOMAIN"] || "localhost:3000" }
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end

  def create
    @name = params[:contacts][:name]
    @last_name = params[:contacts][:last_name]
    @email = params[:contacts][:email]
    @message = params[:contacts][:message]
    mailer
  end

  def sent
  end

  private

  def mailer
    mail = Mailtrap::Sending::Mail.new(
      from:
        {
          email: "mailtrap@www.remcojonk.me",
          name: "Mailtrap Test"
        },
      to: [
        {
          email: "remcojonk@hotmail.com"
        }
      ],
      subject: "New Contact request",
      text: "Name: #{@name} Last Name: #{@last_name} Email: #{@email} Message: #{@message}",
    )

    client = Mailtrap::Sending::Client.new(
      api_key: "********57e2",
      api_host: "https://send.api.mailtrap.io/"
    )

    response = client.send(mail)
    flash[:success] = "Your message has been sent successfully."
    redirect_to :root

  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/portfolio_controller.rb
class PortfolioController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end
end

app/views/contacts/new.html.erb
<div class="px-8 py-6">
    <h1 class="text-4xl text-center">Contact Me</h1>
    <hr>
    <p>I'd love to hear from you. Send me a message below.</p>


    <%= form_for @contact do |form| %>

    <% if @contact.errors.any? %>
        <div id="error_explanation" class="bg-rose-200 pt-3 pb-1 mb-4 px-4 rounded-md">
            <div class="font-bold text-rose-700 text-sm pb-4"><%= pluralize(@contact.errors.count, "error") %> prohibited this page from being saved:</div>

            <ul class="pb-0 mb-0">
                <% @contact.errors.each do |error| %>
                    <li class="text-rose-600 pl-4 text-sm"><%= error.full_message %></li>
                <% end %>
            </ul>
        </div>
    <% end %>


    <div class="field mb-6">
        <%= form.label :name %>
        <%= form.text_field :name %>
    </div>

    <div class="field mb-6">
        <%= form.label :email %>
        <%= form.email_field :email %>
    </div>

    <div class="field">
        <%= form.label :message %>
        <%= form.text_area :message %>
    </div>


    <div class="actions flex justify-end">
        <%= form.submit "Send Message" %>
    </div>
    <% end %>
</div>

app/views/contacts/sent.html.erb
<div class="rounded ">
    <h1>Message Sent!</h1>
    <p>Nice job! You successfully sent me a message. If needed, I will get back to you as soon as possible. In the meantime, check out all my latest articles above.</p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RemcoJonkPortfolio</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Barlow+Condensed:wght@400;600&family=Montserrat&display=swap" rel="stylesheet">
  </head>
  <body>
  <%# NavBar %>
    <%= render 'shared/navbar' %>
    <section class="section" id="home-section">
      <%= render 'shared/header' %>
    </section>
    <%# Portfolio section %>
    <section class="section" id="portfolio-section">
      <%= yield %>
    </section>
    <%# Resume section %>
    <section class="section" id="resume-section">
      <%= render 'shared/resume' %>
    </section>
    <%# Contact section %>
    <section class="section" id="contact-section">
      <%= render 'shared/contact' %>
    </section>
    <%# Footer %>
    <%= render 'shared/footer' %>
  </body>
  <script src="https://code.iconify.design/iconify-icon/1.0.2/iconify-icon.min.js"></script>
</html>

app/views/portfolio/index.html.erb
<div class="container">
  <h2 class="title">Portfolio</h2>
  <%# Project 1 %>
  <div class="project">
    <div class="project-card">
      <%= link_to "https://sail-away.herokuapp.com/", target: "blank", style: "text-decoration: none;" do %>
        <img src="https://res.cloudinary.com/dipnvqfev/image/upload/v1671732532/Portfolio%20Remco/sail_away_d9px30.png" alt="Sail Away">
        <div class="tags">
          <p>Ruby on Rails</p>
          <p>HTML5</p>
          <p>CSS3</p>
        </div>
      <% end %>
    </div>
    <div class="project-description">
      <h2>Sail Away</h2>
      <p>Building time 1 week</p>
      <P>Sail away is a Le Wagon project based on Air BnB. I build this project with a team of 3. My part of the project was building de MVC for the market place</P>
    </div>
  </div>
  <%# Project 2 %>
  <div class="project">
    <div class="project-description">
      <h2>Ghost Writer</h2>
      <p>Building time 2 weeks</p>
      <P>Ghost writer is the end project from the 9 week web development bootcamp. My part of the project was building the MVC for the porfolio end the logic for buying shares</P>
    </div>
    <div class="project-card">
      <%= link_to "https://ghostwriter-invest.herokuapp.com/", target: "blank", style: "text-decoration: none;"  do %>
        <img src="https://res.cloudinary.com/dipnvqfev/image/upload/v1671732546/Portfolio%20Remco/Ghoswriter_a5i07n.png" alt="Ghost Writer">
        <div class="tags">
          <p>Ruby on Rails</p>
          <p>HTML5</p>
          <p>CSS3</p>
          <p>JavaScript</p>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_about-me.html.erb
<div data-tabs-target="tab" id="about">
  <h2>My name is Remco Jonk</h2>

  <p>I have been working as a technician for the past few years, but I am now seeking
  to transition into the tech industry as a full stack developer.</p>

  <p>Early this year, I was inspired to make this career change after meeting several
  experienced developers. To gain a solid foundation in front-end and full stack
  development, I enrolled in a 9-week full-time bootcamp at Le Wagon.</p>

  <p>I am now excited to bring my learned skills and a can-do mentality to your
  company. I am a team player with a strong eagerness to learn new skills and
  technologies. I am confident that my technical expertise and positive attitude
  will make me a valuable addition to your team.</p>
</div>

app/views/shared/_contact.html.erb
<div class="container">
  <div class="title">Contact</div>
  <div class="contact-cards">
    <%# Contact card left: Image and contact details  %>
    <div class="card-left">
      <img id="contact" src="https://res.cloudinary.com/dipnvqfev/image/upload/v1671811527/Portfolio%20Remco/michal-biernat-h0xEUQXzU38-unsplash_qd1axz.jpg" alt="Contact">
      <div class="contact-info">
        <h3>Let's get connected</h3>
        <p>I am availible for front-end or full-stack job offers and or freelance projects.</p>
        <br>
        <p><strong>Phone:</strong> +31 6 23927717</p>
        <p><strong>Email:</strong> remcojonk@hotmail.com</p>
        <p><u>Or find me on:</u></p>
        <div class="socials">
          <a href="https://github.com/remcoj89"> <i class="fa-brands fa-github"></i></a>
          <a href="https://www.linkedin.com/in/remcojonk/"> <i class="fa-brands fa-linkedin"></i></a>
        </div>
      </div>
      ra
    </div>
    <%# Contact card right: Contact form %>
    <div class="card-right">
      <div class="card-message">
        <h1 >Contact Me</h1>
        <p>I'd love to hear from you. Send me a message below.</p>
      </div>
      <div class="contact-form">
        <%= form_with scope: :contacts, url: contacts_path, method: :post, local: true do |form| %>
          <div class="form-group">
            <%= form.label :name %>
            <%= form.text_field :name, class: "form-control" %>
          </div>
          <div class="form-group">
            <%= form.label :last_name %>
            <%= form.text_field :last_name, class: "form-control" %>
          </div>
          <div class="form-group">
            <%= form.label :email %>
            <%= form.email_field :email, class: "form-control" %>
          </div>
          <div class="form-group">
            <%= form.label :message %>
            <%= form.text_area :message, class: "form-control" %>
          </div>
          <%= form.submit "Submit", class: "btn btn-primary" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_experiance.html.erb
<div data-tabs-target="tab" id="experiance">
  <%# Last company %>
  <h4>Field service technician</h4>
  <p>Facta, Uitgeest, The Netherlands, 2017 - 2021</p>
  <ul>
    <li>Meet with the client to determine the problem.</li>
    <li>Consult with the client for the most efficient
      solution.</li>
    <li>Conducting routine equipment servicing out in the
      field.</li>
  </ul>
  <%# First company %>
  <h4>Assistent team leader</h4>
  <p>Royal Dutch Army, The Netherlands, 2007 - 2017</p>
  <ul>
    <li>Responsible for the maintenance program after filed training.</li>
    <li>Teaching basic military skills to the platoon.</li>
    <li>Leading the team in the absence of the commander.</li>
  </ul>
</div>

app/views/shared/_footer.html.erb
<div class="footer">
  <p>©️ RJ Web Development 2023 remcojonk.me All rights reserved</p>
</div>

app/views/shared/_header.html.erb
<div class="header container">

  <div class="cards">
    <div class="card-1">
      <h2>Hello, I am <span>Remco</span></h2>
      <h4>Full-Stack Web Developer</h4>
      <br>
      <p><iconify-icon inline icon="mdi:language-ruby-on-rails" style="color: #d01d00;"></iconify-icon> Ruby on Rails</p>
      <p><iconify-icon icon="material-symbols:mail-rounded" style="color: #fced0a;"></iconify-icon> remcojonk@hotmail.com</p>
      <p><iconify-icon icon="material-symbols:location-on" style="color: #d9d9d9;"></iconify-icon>  Alkmaar, Netherlands</p>
    </div>
    <div class="card-download">
      <h2>Download my resume</h2>
      <div class="button">
        <a href="https://drive.google.com/file/d/1hQiXRrZ5_S52u18WvD5p8MgwVWRqsf9e/view?usp=sharing" class="button-primary" target="blank">Download</a>
        <a href="#contact-section" class="button-primary">Contact</a>
      </div>
    </div>
  </div>
  <div class="image">
    <img id="profile-image"src="https://res.cloudinary.com/dipnvqfev/image/upload/v1671712580/Portfolio%20Remco/Profiel_foto_cg7lad.jpg" alt="">
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar">
  <div class="container">
    <div id="home">
      <button class="btn--scrole-to">Home</button>
    </div>
    <div id="details">
      <button class="btn--scrole-to">Portfolio</button>
      <button class="btn--scrole-to">Resume</button>
      <button class="btn--scrole-to">Contact</button>
    </div>
  </div>
</div>

app/views/shared/_resume.html.erb
<div class="container" data-controller="tabs" data-tabs-default-tab-value="about">
  <div class="title">Resume</div>

  <div class="tab_box" >
    <p class="tab_button" id="about" data-tabs-target="btn" data-action="click->tabs#select">About Me</p>
    <p class="tab_button" id="experiance" data-tabs-target="btn" data-action="click->tabs#select">Experience</p>
    <p class="tab_button" id="skilss" data-tabs-target="btn" data-action="click->tabs#select">Skills</p>
    <p class="tab_button" id="tools" data-tabs-target="btn" data-action="click->tabs#select">Tools</p>
  </div>

  <div class="content-box">
    <%= render 'shared/about-me' %>
    <%= render 'shared/experiance' %>
    <%= render 'shared/skills'  %>
    <%= render 'shared/tools' %>
  </div>
</div>

app/views/shared/_skills.html.erb
<div class="skills" data-tabs-target="tab" id="skilss">
  <div class="skills-card-1">
    <h4>Front end skills</h4>
    <div class="progress-element progress-element--html">
      <p class="progress-label">HTML</p>
      <div class="progress-container">
        <progress max="100" value="60">60%</progress>
      </div>
    </div>
    <div class="progress-element progress-element--css">
      <p class="progress-label">CSS</p>
      <div class="progress-container">
        <progress max="100" value="60">60%</progress>
      </div>
    </div>
    <div class="progress-element progress-element--bootstrap">
      <p class="progress-label">Bootstrap</p>
      <div class="progress-container">
        <progress max="100" value="60">60%</progress>
      </div>
    </div>
    <div class="progress-element progress-element--javascript">
      <p class="progress-label">JavaScript</p>
      <div class="progress-container">
        <progress max="100" value="30">30%</progress>
      </div>
    </div>
  </div>

  <div class="skills-card-2">
    <h4>Back end skills</h4>
    <div class="progress-element progress-element--ruby">
      <p class="progress-label">Ruby on Rails</p>
      <div class="progress-container">
        <progress max="100" value="40">40%</progress>
      </div>
    </div>
    <div class="progress-element progress-element--sql">
      <p class="progress-label">SQL</p>
      <div class="progress-container">
        <progress max="100" value="20">20%</progress>
      </div>
    </div>
    <div class="progress-element progress-element--postgressql">
      <p class="progress-label">PostgreSQL</p>
      <div class="progress-container">
        <progress max="100" value="20">20%</progress>
      </div>
    </div>
    <div class="progress-element progress-element--json">
      <p class="progress-label" >JSON, CSV, XML</p>
      <div class="progress-container">
        <progress max="100" value="15">15%</progress>
      </div>
    </div>
  </div>
</div>

app/views/shared/_tools.html.erb
<div data-tabs-target="tab" id="tools">
  <div class="row">
    <div class="col-6">
      <h4>Tools</h4>
        <p><iconify-icon icon="logos:shopify"></iconify-icon> Shopify</p>
        <p><iconify-icon icon="bi:wordpress" style="color: #207196;"></iconify-icon> Wordpress</p>
        <p><i class="fa-brands fa-git"></i> Git</p>
        <p><i class="fa-brands fa-github"></i>  Github</p>
        <p><iconify-icon icon="logos:heroku-icon" style="color: #207196;"></iconify-icon> Heroku</p>
        <p><iconify-icon icon="vscode-icons:file-type-excel" style="color: #207196;"></iconify-icon> Excel</p>
        <p><iconify-icon icon="vscode-icons:file-type-word" style="color: #207196;"></iconify-icon>  Word</p>
    </div>

    <div class="col-6">
      <h4>Design</h4>
        <p><iconify-icon icon="logos:figma"></iconify-icon> Figma</p>
        <p><iconify-icon icon="logos:adobe-xd"></iconify-icon>  Adobe XD</p>
    </div>
  </div>
</div>